### ISSUE TITLE
홈

### ISSUE THREAD

**Issue by wjddnjswjd12** [d-h-k/airbnb#68]
![화면 기록 2021-05-28 오후 3 05 59 mov](https://user-images.githubusercontent.com/71919983/119937928-8b834d80-bfc6-11eb-9bc2-b83a1c2b9117.gif)
![image](https://user-images.githubusercontent.com/71004200/119936528-48c07600-bfc4-11eb-89e6-358575fe2735.png)
![image](https://user-images.githubusercontent.com/71004200/119936591-6097fa00-bfc4-11eb-9dd3-70a9ea53c821.png)
![image](https://user-images.githubusercontent.com/71004200/119936610-6988cb80-bfc4-11eb-91b8-32c323fef91a.png)
![image](https://user-images.githubusercontent.com/71004200/119936692-86bd9a00-bfc4-11eb-8ed4-4946d8a12615.png)
![image](https://user-images.githubusercontent.com/71004200/119936724-9341f280-bfc4-11eb-9656-f8b9ccddd9b8.png)
![image](https://user-images.githubusercontent.com/71004200/119936780-a81e8600-bfc4-11eb-86cc-5328fbf84373.png)
![image](https://user-images.githubusercontent.com/71004200/119937133-3561da80-bfc5-11eb-88ae-c68ce3400f54.png)

**Comment by moto6** [comment]
![image](https://user-images.githubusercontent.com/31065684/119942789-30088e00-bfcd-11eb-9dc4-156169dcaf2e.png)

**Comment by moto6** [comment]
![image](https://user-images.githubusercontent.com/31065684/119944046-c25d6180-bfce-11eb-8e8e-deb4cdf227de.png)

**Comment by moto6** [comment]
![image](https://user-images.githubusercontent.com/31065684/119950755-26375880-bfd6-11eb-80f9-ff48b8b80515.png)
![image](https://user-images.githubusercontent.com/31065684/119950795-36e7ce80-bfd6-11eb-9e0f-c321035bb866.png)
![image](https://user-images.githubusercontent.com/31065684/119950850-4c5cf880-bfd6-11eb-995c-7b7784e212eb.png)
![image](https://user-images.githubusercontent.com/31065684/119950912-5b43ab00-bfd6-11eb-8e59-cb56381e4dc0.png)
